apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vishwa8333/02-aks-gitops-argo-helm-platform.git
    targetRevision: master
    path: apps/sample-api
  destination:
    server: https://kubernetes.default.svc
    namespace: sample
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

